/**
 * ACC_WARN.md — the developer-facing drift report.
 *
 * Written to the project root on every `acc engine` run so drift is
 * impossible to miss. It captures:
 *
 *   - every code violation the deterministic scan found (ACC0xx
 *     diagnostics with severity error/warn),
 *   - drift in both directions between documentation and code:
 *       · documentation behind code — code does something the
 *         documentation doesn't declare (discovered deps, orphan code,
 *         gaps)
 *       · documentation ahead of code — the documentation promises
 *         something the code no longer does (stale declarations)
 *   - AI findings from the last triggered run (drift / knowledge /
 *     skill+standard gaps) with the supervisor verdict when enabled.
 *
 * The report is deterministic whenever the AI phase is disabled or
 * skipped (no timestamps, stable ordering). It is derived state: it
 * must be gitignored and never counted as repository content.
 */
'use strict';

const path = require('path');

const WARN_FILE = 'ACC_WARN.md';

/** Build the ACC_WARN.md markdown for a completed engine run. */
function buildWarnFile({ scan, ai, sync }) {
  const d = scan.diagnostics_summary;
  const diagnostics = scan.diagnostics.filter((x) => x.severity === 'error' || x.severity === 'warn');
  const gaps = scan.dependency_gaps || [];
  const stale = scan.stale_declarations || [];

  const lines = [];
  lines.push('# ⚠️ ACC WARN — repository drift report');
  lines.push('');
  lines.push('> Auto-generated by `acc engine` on every run. Do not edit —');
  lines.push('> fix the code or the `AGENTS.md` documentation instead. Gitignored.');
  lines.push('');
  lines.push('## Summary');
  lines.push('');
  lines.push(`- Diagnostics: ${d.total} (${d.errors} errors, ${d.warnings} warnings, ${d.infos} infos)`);
  lines.push(`- Docs behind code: ${gaps.length} (code does more than the documentation declares)`);
  lines.push(`- Docs ahead of code: ${stale.length} (documentation promises more than the code does)`);
  const aiOn = ai && ai.enabled && !ai.skipped;
  lines.push(`- AI findings: ${aiOn ? ai.results.length : 0} boundary review(s)${aiOn && ai.supervisor && ai.supervisor.enabled ? ' (supervised)' : ''}`);
  lines.push('');

  // 1. Code violations (deterministic diagnostics).
  lines.push('## Code violations');
  lines.push('');
  if (!diagnostics.length) {
    lines.push('_None — no errors or warnings._');
  } else {
    for (const diag of diagnostics) {
      lines.push(`- **[${diag.code}] ${diag.severity}** \`${diag.path || '.'}\` — ${diag.message}`);
    }
  }
  lines.push('');

  // 2. Docs behind code (discovered drift).
  lines.push('## Docs behind code');
  lines.push('');
  lines.push('> The code has moved ahead of the documentation: these things exist in');
  lines.push('> code but the AGENTS.md files do not declare them. Update the documentation to');
  lines.push('> match the code, or refactor the code back to the declared design.');
  lines.push('');
  if (!gaps.length) {
    lines.push('_None._');
  } else {
    for (const g of gaps) {
      lines.push(`- \`${g.from === '.' ? '.' : g.from}\` depends on \`${g.to}\` — ${g.source}`);
    }
  }
  lines.push('');

  // 3. Docs ahead of code (stale declarations).
  lines.push('## Docs ahead of code');
  lines.push('');
  lines.push('> The documentation promises something the code no longer does: these');
  lines.push('> dependencies are declared but no code references them. Either the code');
  lines.push('> removed the usage (update the documentation) or the documentation was written ahead of');
  lines.push('> the implementation (finish the work or trim the declaration).');
  lines.push('');
  if (!stale.length) {
    lines.push('_None._');
  } else {
    for (const s of stale) {
      lines.push(`- \`${s.from === '.' ? '.' : s.from}\` declares \`${s.to}\` — no code reference found (${s.source})`);
    }
  }
  lines.push('');

  // 4. AI findings (advisory, from the last triggered run).
  if (aiOn) {
    lines.push('## AI findings (last triggered run)');
    lines.push('');
    lines.push('> Advisory — reviewed by the configured model against the changed code.');
    lines.push('> Provenance: memory/inferred. Treat as suggestions, not facts.');
    lines.push('');
    if (!ai.results.length) {
      lines.push('_No boundaries reviewed._');
    } else {
      for (const r of ai.results) {
        const sup = r.supervisor && r.supervisor.enabled;
        const verdict = sup ? ` — supervisor: ${r.supervisor.approved ? 'approved' : 'rejected'} (${r.supervisor.score}/100)` : '';
        lines.push(`### \`${r.dir}\`${verdict}`);
        lines.push('');
        if (!r.drift.length && !r.knowledge.length && !r.skill_gaps.length && !r.standard_gaps.length) {
          lines.push('_No findings._');
          lines.push('');
          continue;
        }
        if (r.drift.length) {
          lines.push('**Drift:**');
          for (const dr of r.drift) {
            const fact = typeof dr === 'string' ? dr : dr.fact;
            const evidence = typeof dr === 'object' && dr && dr.evidence ? ` _(${dr.evidence})_` : '';
            lines.push(`- ${fact}${evidence}`);
          }
          lines.push('');
        }
        if (r.knowledge.length) {
          lines.push('**Knowledge:**');
          for (const k of r.knowledge) lines.push(`- ${k}`);
          lines.push('');
        }
        if (r.skill_gaps.length) {
          lines.push(`**Skill gaps:** ${r.skill_gaps.join(', ')}`);
          lines.push('');
        }
        if (r.standard_gaps.length) {
          lines.push(`**Standard gaps:** ${r.standard_gaps.join(', ')}`);
          lines.push('');
        }
        if (sup && r.supervisor.issues && r.supervisor.issues.length) {
          lines.push('**Supervisor issues:**');
          for (const i of r.supervisor.issues) lines.push(`- ${i}`);
          lines.push('');
        }
      }
    }
    lines.push('');
  }

  // 5. Footer: how to resolve.
  lines.push('---');
  lines.push('');
  lines.push('Resolve drift by updating `AGENTS.md` (documentation behind code) or the code');
  lines.push('(documentation ahead of code), then re-run `acc engine`. This file regenerates');
  lines.push('on every run and disappears from the warning list when clean.');
  lines.push('');

  return { file: WARN_FILE, text: lines.join('\n') };
}

/** Write ACC_WARN.md to the project root. Returns the path written. */
function writeWarnFile(root, report) {
  const file = path.join(root, WARN_FILE);
  const { mkdirSync, writeFileSync } = require('fs');
  writeFileSync(file, report.text);
  return WARN_FILE;
}

/** Build the compact summary object surfaced in engine JSON output. */
function warnSummary(scan, ai) {
  const d = scan.diagnostics_summary;
  const aiOn = ai && ai.enabled && !ai.skipped;
  const approved = aiOn && ai.results.every((r) => !r.supervisor || !r.supervisor.enabled || r.supervisor.approved);
  // `diagnostics` counts only error/warn (what the report actually lists);
  // info-level observations (e.g. ACC062) are not violations.
  const violations = (scan.diagnostics || []).filter((x) => x.severity === 'error' || x.severity === 'warn').length;
  return {
    file: WARN_FILE,
    diagnostics: violations,
    errors: d.errors,
    warnings: d.warnings,
    docs_behind_code: (scan.dependency_gaps || []).length,
    docs_ahead_of_code: (scan.stale_declarations || []).length,
    ai_findings: aiOn ? ai.results.length : 0,
    supervisor_approved: aiOn && ai.supervisor && ai.supervisor.enabled ? approved : null,
  };
}

module.exports = { buildWarnFile, writeWarnFile, warnSummary, WARN_FILE };
